<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>iem-verifier</AssemblyName>
    <RootNamespace>IEM.Verifier</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IEM.Verification\IEM.Verification.csproj" />
  </ItemGroup>

</Project>
