#!/bin/sh
set -e

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl stop internet-evidence-monitor.service || true
    systemctl disable internet-evidence-monitor.service || true
fi

exit 0
